name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semver of the version to deploy"
        required: true
      environment:
        description: "Target environment name"
        required: true

jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: |
          echo "Deploying version ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }}"
